### ISSUE TITLE
[dev-mvp]: concern_points are not being passed through POST /safe_paths

### ISSUE THREAD

**Issue by zmon** [Path-Check/safeplaces-frontend#56] opened 2020-05-04 20:45 UTC
Steps to reproduce:

1. Set backend to true
2. Load data and save in redaction tool
3. Load data and save in publishing tool

Expected results:
Data POST /safe_paths contains an array of `concern_points`

Actual result:
`concern_points` is not passed

Possible solution:

in `saveText()`, move the code that creates the `concern_points` from the code handling no backend to just before the check for the backend.  This way both publishing to a backend or file contains the `concern_points`.

Found in 369a47

**Comment by AdamLeonSmith** [comment] 2020-05-05 09:51
I'm not able to reproduce this:

![image](https://user-images.githubusercontent.com/48051844/81054287-6a812380-8ebe-11ea-84bd-c991ce6de4c7.png)

Can you expand on the issue?

**Comment by krishnadurai** [comment] 2020-05-05 10:05
@zmon @AdamLeonSmith We are ignoring concern points in both frontend and backend for POST /safe_path API. This field is just kept for backwards compatibility.

The understanding is that /GET safe_paths will return all 'redacted_trails' co-ordinates within its most recently published start_date and end_date for an organization.

cc @mundanelunacy

**Comment by krishnadurai** [comment] 2020-05-05 10:20
To explain further:

So the flow @mundanelunacy discussed with me is:
1. HA will redact trails and save them.
1. HA publishes trails by entering start_date and end_date.
1. HA, while publishing trails, does not edit any trails - just the start and end dates.
1. /GET safe_paths/<org_id> returns concerned_points between the start_date and end_date from the last published entry for that organization_id.

**Comment by zmon** [comment] 2020-05-05 21:02
@krishnadurai Thank you for the clarification.  We are running our own API server (two or three weeks old) for a POC/Demo and grabbed the newer front end.

I will let you close this issue.

**Comment by AdamLeonSmith** [comment] 2020-05-06 13:54
Closing this per above.

**Closed by AdamLeonSmith** 2020-05-06 13:54 UTC
