### ISSUE TITLE
Store and Auto population of Health Authority attributes (new field notification URL)

### ISSUE THREAD

**Issue by kylemtowle** [Path-Check/safeplaces-frontend#26] opened 2020-04-27 00:39 UTC
Has_Backend

Change API spec and publisher form to include the new following fields: Notification URL to safe_paths.json
Save Notification URL via API Spec
On Load of Redacted trails, retrieve Notification URL

No_Backend

Change publisher form to include the new following field: Notification URL to safe_paths.json
Add "Load safe_paths.json" option in the Publisher tool to specify the location of an existing safe_paths.json.
Still support "loading redacted" to add to the lat/long/time data points prior to publishing a new safe_paths.json

Update API Spec to reflect new attribute: Notification UR
Update backend to store/retrieve new attribute: Notification UR

**Comment by mundanelunacy** [comment] 2020-04-28 16:07
@kylemtowle 

Has_backend is description is clear and should be doable.

No_Backend description is not so clear.  Could we maybe have a mockup of what you mean?

**Comment by kylemtowle** [comment] 2020-04-28 17:29
This might be tougher to explain without a mockup:
Change publisher form to include the new following field: Notification URL to safe_paths.json
Add "Load safe_paths.json" option in the Publisher tool to specify the location of an existing safe_paths.json.
Still support "loading redacted" to add to the lat/long/time data points prior to publishing a new safe_paths.json

Because the values of the fields themselves would only be in safe_paths.json file, that's why I'm suggesting we provide that option. It will also load all current concern points. Plus we allow load single redaction file (current functionality) to be done after loading an existing safe_paths.json (if this wasn't the first use)

**Comment by mundanelunacy** [comment] 2020-04-29 15:31
Got it.  

I suggest we table the No_backend case for `dev_react`

The problem is that the [server spec](https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/Safe-Places-Server.md)  `GET /redacted_trails` and `safe_paths.json` are formatted differently (whyyyy?)

This means that we can't reuse Steve's code to import concern points from `safe_paths.json`. We'd have to write a new parser to do this and this would take time, and potentially introduce bugs.  

Also, sounded like Robert and Adi might be able to get `dev_react` out soon.

**Comment by kylemtowle** [comment] 2020-04-29 17:09
That's fine...we would need to make sure we can update the demo version of the tool with a backend = true capability (when we switch to react version) to gain this auto-populate at some point. I agree with your conclusion though.
    On Wednesday, April 29, 2020, 08:31:33 AM PDT, Satoshi Kawase <notifications@github.com> wrote:  
 
 


Got it.

I suggest we table the No_backend case for dev_react

The problem is that the server spec GET /redacted_trails and safe_paths.json are formatted differently (whyyyy?)

This means that we can't reuse Steve's code to import concern points from safe_paths.json. We'd have to write a new parser to do this and this would take time, and potentially introduce bugs.

Also, sounded like Robert and Adi might be able to get dev_react out soon.

**Comment by AdamLeonSmith** [comment] 2020-05-01 09:54
I just tested this on the dev_mvp with a backend.  Notification URL is populated in the UI but the POST on publish doesn't include the field:

`{"datetime_created":"Fri, 27 Mar 2020 04:32:12 GMT","organization_id":"a88309c2-26cd-4d2b-8923-af0779e423a3","safe_path":{"authority_name":"Fake Organization","concern_points":[{"latitude":12.34,"longitude":12.34,"time":123},{"latitude":12.34,"longitude":12.34,"time":456}],"info_website":"https://www.something.gov/path/to/info/website","publish_date_utc":1584924583},"user_id":"a88309c1-26cd-4d2b-8923-af0779e423a3"}`

![image](https://user-images.githubusercontent.com/48051844/80797550-05fe5580-8b9a-11ea-91b6-d74a4d20d22e.png)

**Comment by mundanelunacy** [comment] 2020-05-04 06:02
@AdamLeonSmith Fixed on staging.

**Closed by mundanelunacy** 2020-05-04 06:02 UTC
Labels: enhancement
